name: mace_al_clean
channels:
  - defaults
dependencies:
  - python=3.11.11
  - pip=25.0
  - setuptools=75.8.0
  - wheel=0.45.1
  - ncurses
  - openssl
  - readline
  - sqlite
  - tk
  - xz
  - zlib
  - libffi
  - libgcc-ng
  - libstdcxx-ng
  - bzip2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - ase==3.24.0
      - attrs==25.3.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - configargparse==1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - e3nn==0.4.4
      - filelock==3.13.1
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h5py==3.13.0
      - idna==3.4
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lightning-utilities==0.14.2
      - lmdb==1.6.2
      - mace-torch==0.3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - matscipy==1.1.1
      - mpi4py==4.0.3
      - mpmath==1.3.0
      - multidict==6.2.0
      - networkx==3.3
      - numpy==1.26.4
      - openmm==8.2.0
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - orjson==3.10.15
      - packaging==24.2
      - pandas==2.2.3
      - periodictable==2.0.2
      - pexpect==4.9.0
      - pillow==11.0.0
      - prettytable==3.15.1
      - propcache==0.3.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-hostlist==2.2.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - requests==2.28.1
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch-ema==0.3
      - torchmetrics==1.7.0
      - tqdm==4.67.1
      - triton==2.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==1.26.13
      - wcwidth==0.2.13
      - yarl==1.18.3
