# MACE
args_dict: {
    "name": "MACE_on_bi11-3_samples",
    "num_workers": 16,
    "train_file": "train.xyz",
    "valid_file": "test.xyz",
    "test_file": "test.xyz",
    "results_dir": "results",
    "E0s": "average",
    # "E0s": {83: -5802.83},
    "statistics_file": None,
    # "model": "CoulumbMACE",
    # "model": "ScaleShiftMACE",
    "model": "MACE_with_charge",
    "force_weight": 100.0,
    "energy_weight": 1.0,
    "num_interactions": 2,
    "num_channels": 128,
    "max_L": 1,
    "r_max": 9.0,
    "patience": 20,
    "correlation": 3,
    "batch_size": 32,
    "valid_batch_size": 32,
    "max_num_epochs": 300,
    "scaling": "rms_forces_scaling",
    "swa": False,  # Flags set to True if present
    # "start_swa": 60,
    "ema": True,
    "ema_decay": 0.99,
    "amsgrad": True,
    "error_table": "TotalMAE",
    "device": "cuda",
    "seed": 123,
    "scale": True,
    "shift": True
}
